config/routes.rb
Rails.application.routes.draw do
  resources :vessels
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vessel.rb
class Vessel < ApplicationRecord
  validates :name, :vessel_id, :vessel_type, presence: true

  def hail_sign
    return "#{self.vessel_id} - #{self.name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/vessels_controller.rb
class VesselsController < ApplicationController
  before_action :set_vessel, only: [:show, :edit, :update, :destroy]

  # GET /vessels
  # GET /vessels.json
  def index
    @vessels = Vessel.all
  end

  # GET /vessels/1
  # GET /vessels/1.json
  def show
  end

  # GET /vessels/new
  def new
    @vessel = Vessel.new
  end

  # GET /vessels/1/edit
  def edit
  end

  # POST /vessels
  # POST /vessels.json
  def create
    @vessel = Vessel.new(vessel_params)

    respond_to do |format|
      if @vessel.save
        format.html { redirect_to @vessel, notice: 'Vessel was successfully created.' }
        format.json { render :show, status: :created, location: @vessel }
      else
        format.html { render :new }
        format.json { render json: @vessel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vessels/1
  # PATCH/PUT /vessels/1.json
  def update
    respond_to do |format|
      if @vessel.update(vessel_params)
        format.html { redirect_to @vessel, notice: 'Vessel was successfully updated.' }
        format.json { render :show, status: :ok, location: @vessel }
      else
        format.html { render :edit }
        format.json { render json: @vessel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vessels/1
  # DELETE /vessels/1.json
  def destroy
    @vessel.destroy
    respond_to do |format|
      format.html { redirect_to vessels_url, notice: 'Vessel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vessel
      @vessel = Vessel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vessel_params
      params.require(:vessel).permit(:name, :vessel_id, :vessel_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vessels_helper.rb
module VesselsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vessels</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vessels/_form.html.erb
<%= form_with(model: vessel, local: true) do |form| %>
  <% if vessel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vessel.errors.count, "error") %> prohibited this vessel from being saved:</h2>

      <ul>
      <% vessel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :vessel_name %>
  </div>

  <div class="field">
    <%= form.label :vessel_id %>
    <%= form.text_field :vessel_id, id: :vessel_vessel_id %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :vessel_type, id: :vessel_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vessels/edit.html.erb
<h1>Editing Vessel</h1>

<%= render 'form', vessel: @vessel %>

<%= link_to 'Show', @vessel %> |
<%= link_to 'Back', vessels_path %>

app/views/vessels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vessels</h1>

<table>
  <thead>
    <tr>
      <th>Hail Sign</th>
      <th>Name</th>
      <th>Vessel</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vessels.each do |vessel| %>
      <tr>
        <td><%= vessel.hail_sign %></td>
        <td><%= vessel.name %></td>
        <td><%= vessel.vessel_id %></td>
        <td><%= vessel.vessel_type %></td>
        <td><%= link_to 'Show', vessel %></td>
        <td><%= link_to 'Edit', edit_vessel_path(vessel) %></td>
        <td><%= link_to 'Destroy', vessel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vessel', new_vessel_path %>

app/views/vessels/new.html.erb
<h1>New Vessel</h1>

<%= render 'form', vessel: @vessel %>

<%= link_to 'Back', vessels_path %>

app/views/vessels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hail Sign:</strong>
  <%= @vessel.hail_sign %>
</p>

<p>
  <strong>Name:</strong>
  <%= @vessel.name %>
</p>

<p>
  <strong>ID:</strong>
  <%= @vessel.vessel_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @vessel.vessel_type %>
</p>

<%= link_to 'Edit', edit_vessel_path(@vessel) %> |
<%= link_to 'Back', vessels_path %>